import type { Event } from '@models/event.types';

// Helper: fake Firestore Timestamp from JS Date
// Cast Date as `any` so it passes the `instanceof Date` branch in toDate()
const ts = (d: Date) => d as any;

const geo = (lat: number, lng: number) =>
  ({ latitude: lat, longitude: lng } as any);

// ── South African Provinces ──────────────────────────────────────────────────
export interface Province {
  id: string;
  label: string;
  short: string;
  emoji: string;
  cities: string[];
}

export const PROVINCES: Province[] = [
  { id: 'all',  label: 'All of SA',      short: 'All SA',     emoji: '🇿🇦', cities: [] },
  { id: 'WC',   label: 'Western Cape',   short: 'W. Cape',    emoji: '🏔️', cities: ['Cape Town', 'Stellenbosch', 'George', 'Paarl', 'Knysna'] },
  { id: 'GP',   label: 'Gauteng',        short: 'Gauteng',    emoji: '🌆', cities: ['Johannesburg', 'Pretoria', 'Sandton', 'Soweto', 'Midrand'] },
  { id: 'KZN',  label: 'KwaZulu-Natal',  short: 'KZN',        emoji: '🌊', cities: ['Durban', 'Pietermaritzburg', 'Umhlanga', 'Richards Bay', 'Ballito'] },
  { id: 'EC',   label: 'Eastern Cape',   short: 'E. Cape',    emoji: '🌅', cities: ['Gqeberha', 'East London', 'Makhanda', 'Queenstown'] },
  { id: 'FS',   label: 'Free State',     short: 'Free State', emoji: '🌾', cities: ['Bloemfontein', 'Welkom', 'Bethlehem', 'Phuthaditjhaba'] },
  { id: 'LP',   label: 'Limpopo',        short: 'Limpopo',    emoji: '🦁', cities: ['Polokwane', 'Tzaneen', 'Mokopane', 'Bela-Bela'] },
  { id: 'MP',   label: 'Mpumalanga',     short: 'Mpumalanga', emoji: '🌿', cities: ['Mbombela', 'Witbank', 'Secunda', 'Lydenburg'] },
  { id: 'NW',   label: 'North West',     short: 'N. West',    emoji: '💎', cities: ['Rustenburg', 'Mahikeng', 'Potchefstroom', 'Klerksdorp'] },
  { id: 'NC',   label: 'Northern Cape',  short: 'N. Cape',    emoji: '🏜️', cities: ['Kimberley', 'Upington', 'Springbok', 'De Aar'] },
];

const MOCK_EVENT_SEED: Event[] = [
  {
    id: 'mock-1',
    title: 'Afrobeats All Night',
    description: 'Cape Town\'s hottest Afrobeats night. Four floors of sound, top DJs from Lagos, Nairobi and Jo\'burg. Dress to impress.',
    category: 'nightlife',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-23T20:00:00')),
    endDate: ts(new Date('2026-05-24T04:00:00')),
    venueName: 'The Assembly',
    address: '61 Harrington St',
    city: 'Cape Town',
    location: geo(-33.9249, 18.4241),
    totalCapacity: 600,
    totalBooked: 487,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'General', price: 18000, currency: 'ZAR', capacity: 400, sold: 360, },
      { id: 't2', name: 'VIP', price: 45000, currency: 'ZAR', capacity: 200, sold: 127, },
    ],
    hostId: 'host-1',
    hostName: 'Rhythm Republic',
    tags: ['afrobeats', 'dance', 'nightlife', 'dj'],
    featured: true,
    featuredOrder: 1,
    viewCount: 3420,
    saveCount: 241,
    createdAt: ts(new Date('2026-05-01')),
    updatedAt: ts(new Date('2026-05-15')),
  },
  {
    id: 'mock-2',
    title: 'Cape Town Electronic Festival',
    description: 'Three stages, 24 hours of non-stop electronic music featuring the biggest names in house, techno and drum & bass.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-24T22:00:00')),
    endDate: ts(new Date('2026-05-25T10:00:00')),
    venueName: 'Cape Town Stadium Precinct',
    address: 'Fritz Sonnenberg Rd',
    city: 'Cape Town',
    location: geo(-33.9067, 18.4137),
    totalCapacity: 5000,
    totalBooked: 4102,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Early Bird', price: 35000, currency: 'ZAR', capacity: 2000, sold: 2000, },
      { id: 't2', name: 'Standard', price: 55000, currency: 'ZAR', capacity: 3000, sold: 2102, },
    ],
    hostId: 'host-2',
    hostName: 'Electronic Arts CT',
    tags: ['electronic', 'techno', 'house', 'festival'],
    featured: true,
    featuredOrder: 2,
    viewCount: 12840,
    saveCount: 890,
    createdAt: ts(new Date('2026-04-01')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-3',
    title: 'Street Food Festival',
    description: 'Over 60 local vendors bringing the best street food from across Africa and beyond. Live music, craft beer and good vibes.',
    category: 'food',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-25T12:00:00')),
    endDate: ts(new Date('2026-05-25T22:00:00')),
    venueName: 'Oranjezicht City Farm',
    address: 'De Waal Dr',
    city: 'Cape Town',
    location: geo(-33.9310, 18.4134),
    totalCapacity: 1500,
    totalBooked: 820,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Entry', price: 8000, currency: 'ZAR', capacity: 1500, sold: 820, },
    ],
    hostId: 'host-3',
    hostName: 'Cape Town Eats',
    tags: ['food', 'streetfood', 'market', 'family'],
    featured: true,
    featuredOrder: 3,
    viewCount: 6200,
    saveCount: 445,
    createdAt: ts(new Date('2026-04-20')),
    updatedAt: ts(new Date('2026-05-10')),
  },
  {
    id: 'mock-4',
    title: 'Jazz & Wine Evening',
    description: 'An intimate evening of world-class jazz paired with award-winning Stellenbosch wines. Limited tickets — book now.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-30T19:00:00')),
    endDate: ts(new Date('2026-05-30T23:00:00')),
    venueName: 'Winchester Mansions Hotel',
    address: '221 Beach Rd, Sea Point',
    city: 'Cape Town',
    location: geo(-33.9171, 18.3979),
    totalCapacity: 120,
    totalBooked: 98,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'General', price: 25000, currency: 'ZAR', capacity: 80, sold: 68, },
      { id: 't2', name: 'Premium (incl. wine pairing)', price: 45000, currency: 'ZAR', capacity: 40, sold: 30, },
    ],
    hostId: 'host-4',
    hostName: 'Jazz Cape Town',
    tags: ['jazz', 'wine', 'intimate', 'classy'],
    featured: false,
    viewCount: 1840,
    saveCount: 112,
    createdAt: ts(new Date('2026-05-05')),
    updatedAt: ts(new Date('2026-05-12')),
  },
  {
    id: 'mock-5',
    title: 'Comedy Night Live',
    description: 'SA\'s top stand-up comedians take the stage. Prepare to laugh until it hurts. Strictly 18+.',
    category: 'arts',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-06T20:00:00')),
    endDate: ts(new Date('2026-06-06T23:00:00')),
    venueName: 'On Broadway',
    address: 'Somerset Rd, Green Point',
    city: 'Cape Town',
    location: geo(-33.9183, 18.4099),
    totalCapacity: 300,
    totalBooked: 224,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Standard', price: 15000, currency: 'ZAR', capacity: 300, sold: 224, },
    ],
    hostId: 'host-5',
    hostName: 'Laugh Factory SA',
    tags: ['comedy', 'standup', 'entertainment', '18+'],
    featured: false,
    viewCount: 2100,
    saveCount: 178,
    createdAt: ts(new Date('2026-05-08')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-6',
    title: 'Sunrise Beach Yoga',
    description: 'Start your Sunday with a guided 90-min vinyasa yoga session on the beach as the sun rises over the Atlantic.',
    category: 'sports',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-07T06:30:00')),
    endDate: ts(new Date('2026-06-07T08:00:00')),
    venueName: 'Camps Bay Beach',
    address: 'Victoria Rd',
    city: 'Cape Town',
    location: geo(-33.9500, 18.3795),
    totalCapacity: 40,
    totalBooked: 32,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Session pass', price: 5000, currency: 'ZAR', capacity: 40, sold: 32, },
    ],
    hostId: 'host-6',
    hostName: 'Flow & Soul',
    tags: ['yoga', 'wellness', 'beach', 'sunrise'],
    featured: false,
    viewCount: 980,
    saveCount: 67,
    createdAt: ts(new Date('2026-05-10')),
    updatedAt: ts(new Date('2026-05-13')),
  },
  {
    id: 'mock-7',
    title: 'Rooftop Networking Social',
    description: 'Connect with Cape Town\'s brightest minds in tech, design and startups. Sundowners, finger food and good conversation.',
    category: 'social',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-11T18:00:00')),
    endDate: ts(new Date('2026-06-11T21:00:00')),
    venueName: 'Workshop17 Watershed',
    address: 'V&A Waterfront',
    city: 'Cape Town',
    location: geo(-33.9063, 18.4218),
    totalCapacity: 200,
    totalBooked: 134,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Ticket', price: 20000, currency: 'ZAR', capacity: 200, sold: 134, },
    ],
    hostId: 'host-7',
    hostName: 'Cape Town Founders Club',
    tags: ['networking', 'startup', 'tech', 'social'],
    featured: false,
    viewCount: 1560,
    saveCount: 89,
    createdAt: ts(new Date('2026-05-09')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-8',
    title: 'Art & Design Market',
    description: 'Browse and buy original work from 80+ Cape Town artists and designers. Free entry. All styles, all mediums.',
    category: 'arts',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-14T10:00:00')),
    endDate: ts(new Date('2026-06-14T18:00:00')),
    venueName: 'Woodstock Exchange',
    address: '66 Albert Rd, Woodstock',
    city: 'Cape Town',
    location: geo(-33.9302, 18.4548),
    totalCapacity: 800,
    totalBooked: 210,
    isFree: true,
    ticketTiers: [],
    hostId: 'host-8',
    hostName: 'Creative Cape Town',
    tags: ['art', 'design', 'market', 'free'],
    featured: false,
    viewCount: 2340,
    saveCount: 204,
    createdAt: ts(new Date('2026-05-07')),
    updatedAt: ts(new Date('2026-05-12')),
  },
  {
    id: 'mock-9',
    title: 'Braai & Beats',
    description: 'A long-table braai with live local bands and ice-cold beverages. Bring your appetite and your dancing shoes.',
    category: 'food',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-21T15:00:00')),
    endDate: ts(new Date('2026-06-21T22:00:00')),
    venueName: 'Devil\'s Peak Brewing Co.',
    address: '95 Durham Ave, Salt River',
    city: 'Cape Town',
    location: geo(-33.9306, 18.4602),
    totalCapacity: 350,
    totalBooked: 128,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'All-inclusive', price: 12000, currency: 'ZAR', capacity: 350, sold: 128, },
    ],
    hostId: 'host-3',
    hostName: 'Cape Town Eats',
    tags: ['braai', 'food', 'live music', 'outdoor'],
    featured: false,
    viewCount: 1200,
    saveCount: 91,
    createdAt: ts(new Date('2026-05-11')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-10',
    title: 'Sunset 5K Beach Run',
    description: 'A social fun run along the Sea Point promenade. All paces welcome. Medal, t-shirt and post-race snacks included.',
    category: 'sports',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-28T17:30:00')),
    endDate: ts(new Date('2026-06-28T20:00:00')),
    venueName: 'Sea Point Promenade',
    address: 'Beach Rd, Sea Point',
    city: 'Cape Town',
    location: geo(-33.9175, 18.3952),
    totalCapacity: 500,
    totalBooked: 287,
    isFree: false,
    ticketTiers: [
      { id: 't1', name: 'Entry', price: 5000, currency: 'ZAR', capacity: 500, sold: 287, },
    ],
    hostId: 'host-6',
    hostName: 'Flow & Soul',
    tags: ['running', '5k', 'beach', 'fitness'],
    featured: false,
    viewCount: 1780,
    saveCount: 143,
    createdAt: ts(new Date('2026-05-06')),
    updatedAt: ts(new Date('2026-05-13')),
  },

  // ── GAUTENG ─────────────────────────────────────
  {
    id: 'mock-gp-1',
    title: 'Afro Soul Sessions',
    description: 'Jo\'burg\'s premier Afro-soul night at the iconic Bassline. Three rooms, handpicked DJs, premium bar.',
    category: 'nightlife',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-24T20:00:00')),
    endDate: ts(new Date('2026-05-25T04:00:00')),
    venueName: 'Bassline Live',
    address: '10 Henry Nxumalo St, Newtown',
    city: 'Johannesburg',
    location: geo(-26.2003, 28.0345),
    totalCapacity: 800,
    totalBooked: 612,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'General', price: 20000, currency: 'ZAR', capacity: 800, sold: 612 }],
    hostId: 'host-gp-1',
    hostName: 'Joburg Nights',
    tags: ['afrosoul', 'dance', 'nightlife'],
    featured: true,
    featuredOrder: 4,
    viewCount: 4100,
    saveCount: 310,
    createdAt: ts(new Date('2026-05-01')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-gp-2',
    title: 'Constitution Hill Night Market',
    description: 'Evening market in the historic Constitution Hill precinct. Local food stalls, craft vendors and live acoustic sets.',
    category: 'food',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-30T16:00:00')),
    endDate: ts(new Date('2026-05-30T22:00:00')),
    venueName: 'Constitution Hill',
    address: '1 Kotze St, Braamfontein',
    city: 'Johannesburg',
    location: geo(-26.1869, 28.0445),
    totalCapacity: 1200,
    totalBooked: 430,
    isFree: true,
    ticketTiers: [],
    hostId: 'host-gp-2',
    hostName: 'Jozi Markets',
    tags: ['market', 'food', 'craft', 'free'],
    featured: false,
    viewCount: 2800,
    saveCount: 198,
    createdAt: ts(new Date('2026-05-05')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-gp-3',
    title: 'Pretoria Startup Summit',
    description: 'Two days of talks, workshops and networking for SA\'s growing startup ecosystem. Speakers from Silicon Valley to Silicon Cape.',
    category: 'corporate',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-03T09:00:00')),
    endDate: ts(new Date('2026-06-04T17:00:00')),
    venueName: 'CSIR International Convention Centre',
    address: 'Meiring Naudé Rd, Brummeria',
    city: 'Pretoria',
    location: geo(-25.7476, 28.2753),
    totalCapacity: 2000,
    totalBooked: 1450,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Full Pass', price: 85000, currency: 'ZAR', capacity: 2000, sold: 1450 }],
    hostId: 'host-gp-3',
    hostName: 'SA Founders Network',
    tags: ['startup', 'tech', 'summit', 'networking'],
    featured: false,
    viewCount: 5600,
    saveCount: 421,
    createdAt: ts(new Date('2026-04-15')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-gp-4',
    title: 'Sandton Jazz Lawn Series',
    description: 'Luxury outdoor jazz on the lawns of Sandton. Gourmet food trucks, sparkling wine and SA\'s best jazz ensembles.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-07T15:00:00')),
    endDate: ts(new Date('2026-06-07T21:00:00')),
    venueName: 'Nelson Mandela Square',
    address: 'Maude St, Sandton',
    city: 'Sandton',
    location: geo(-26.1076, 28.0567),
    totalCapacity: 500,
    totalBooked: 388,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Lawn Ticket', price: 30000, currency: 'ZAR', capacity: 500, sold: 388 }],
    hostId: 'host-gp-4',
    hostName: 'Joburg Jazz Society',
    tags: ['jazz', 'outdoor', 'luxury', 'live music'],
    featured: false,
    viewCount: 3200,
    saveCount: 267,
    createdAt: ts(new Date('2026-05-08')),
    updatedAt: ts(new Date('2026-05-14')),
  },

  // ── KWAZULU-NATAL ────────────────────────────────
  {
    id: 'mock-kzn-1',
    title: 'Durban Beachfront Festival',
    description: 'The biggest outdoor festival on the KZN coast. Eight stages, 40+ acts, street food and ocean views. A true Durban summer experience.',
    category: 'festivals',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-05-26T12:00:00')),
    endDate: ts(new Date('2026-05-26T23:00:00')),
    venueName: 'North Beach Durban',
    address: 'Marine Parade, North Beach',
    city: 'Durban',
    location: geo(-29.8579, 31.0292),
    totalCapacity: 8000,
    totalBooked: 6200,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Standard', price: 25000, currency: 'ZAR', capacity: 8000, sold: 6200 }],
    hostId: 'host-kzn-1',
    hostName: 'Durban Events Co.',
    tags: ['festival', 'beach', 'outdoor', 'durban'],
    featured: true,
    featuredOrder: 5,
    viewCount: 9800,
    saveCount: 720,
    createdAt: ts(new Date('2026-04-10')),
    updatedAt: ts(new Date('2026-05-15')),
  },
  {
    id: 'mock-kzn-2',
    title: 'Umhlanga Sundowner Cruise',
    description: 'Set sail from Wilson\'s Wharf for a 3-hour sunset cruise with canapes, cocktails and live acoustic music.',
    category: 'social',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-05T17:30:00')),
    endDate: ts(new Date('2026-06-05T20:30:00')),
    venueName: 'Wilson\'s Wharf Marina',
    address: 'Boatman\'s Rd, Point',
    city: 'Durban',
    location: geo(-29.8709, 31.0390),
    totalCapacity: 80,
    totalBooked: 62,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Cruise Ticket', price: 55000, currency: 'ZAR', capacity: 80, sold: 62 }],
    hostId: 'host-kzn-2',
    hostName: 'Coastal Events DBN',
    tags: ['cruise', 'sundowner', 'social', 'cocktails'],
    featured: false,
    viewCount: 2100,
    saveCount: 178,
    createdAt: ts(new Date('2026-05-09')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-kzn-3',
    title: 'Zulu Heritage Cultural Show',
    description: 'A vibrant celebration of Zulu culture — traditional dance, storytelling, craft market and authentic food.',
    category: 'arts',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-14T10:00:00')),
    endDate: ts(new Date('2026-06-14T18:00:00')),
    venueName: 'Shakaland Cultural Village',
    address: 'R66, Eshowe',
    city: 'Pietermaritzburg',
    location: geo(-29.6006, 30.3799),
    totalCapacity: 600,
    totalBooked: 210,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Entry', price: 18000, currency: 'ZAR', capacity: 600, sold: 210 }],
    hostId: 'host-kzn-3',
    hostName: 'KZN Heritage Trust',
    tags: ['zulu', 'culture', 'heritage', 'dance'],
    featured: false,
    viewCount: 1400,
    saveCount: 95,
    createdAt: ts(new Date('2026-05-10')),
    updatedAt: ts(new Date('2026-05-15')),
  },

  // ── EASTERN CAPE ─────────────────────────────────
  {
    id: 'mock-ec-1',
    title: 'Gqeberha Jazz Festival',
    description: 'Three days of world-class jazz in the Friendly City. Featuring local legends and international guests on the waterfront stage.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-19T14:00:00')),
    endDate: ts(new Date('2026-06-21T22:00:00')),
    venueName: 'Boardwalk Convention Centre',
    address: 'Marine Dr, Summerstrand',
    city: 'Gqeberha',
    location: geo(-33.9860, 25.6731),
    totalCapacity: 3000,
    totalBooked: 1800,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Weekend Pass', price: 45000, currency: 'ZAR', capacity: 3000, sold: 1800 }],
    hostId: 'host-ec-1',
    hostName: 'Eastern Cape Arts',
    tags: ['jazz', 'festival', 'waterfront', 'live music'],
    featured: false,
    viewCount: 3400,
    saveCount: 245,
    createdAt: ts(new Date('2026-05-03')),
    updatedAt: ts(new Date('2026-05-15')),
  },
  {
    id: 'mock-ec-2',
    title: 'East London Surf Pro',
    description: 'Watch SA\'s best surfers compete in the annual East London surfing championships at iconic Nahoon Reef.',
    category: 'sports',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-20T08:00:00')),
    endDate: ts(new Date('2026-06-20T17:00:00')),
    venueName: 'Nahoon Reef',
    address: 'Nahoon Beach Rd',
    city: 'East London',
    location: geo(-33.0041, 27.9263),
    totalCapacity: 2000,
    totalBooked: 650,
    isFree: true,
    ticketTiers: [],
    hostId: 'host-ec-2',
    hostName: 'SA Surf Federation',
    tags: ['surf', 'competition', 'beach', 'free'],
    featured: false,
    viewCount: 1900,
    saveCount: 132,
    createdAt: ts(new Date('2026-05-07')),
    updatedAt: ts(new Date('2026-05-13')),
  },

  // ── FREE STATE ────────────────────────────────────
  {
    id: 'mock-fs-1',
    title: 'Mangaung African Cultural Festival',
    description: 'MACUFE — the biggest arts and culture festival in SA\'s interior. Music, theatre, visual art and heritage celebrations.',
    category: 'festivals',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1508997449629-303059a039c0?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-25T10:00:00')),
    endDate: ts(new Date('2026-06-28T22:00:00')),
    venueName: 'Sand du Plessis Theatre',
    address: 'Markgraaf St, Westdene',
    city: 'Bloemfontein',
    location: geo(-29.1193, 26.2141),
    totalCapacity: 5000,
    totalBooked: 3100,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Festival Pass', price: 35000, currency: 'ZAR', capacity: 5000, sold: 3100 }],
    hostId: 'host-fs-1',
    hostName: 'MACUFE Foundation',
    tags: ['macufe', 'culture', 'arts', 'festival'],
    featured: false,
    viewCount: 4200,
    saveCount: 310,
    createdAt: ts(new Date('2026-05-01')),
    updatedAt: ts(new Date('2026-05-14')),
  },
  {
    id: 'mock-fs-2',
    title: 'Bloemfontein Food Market',
    description: 'The heartland\'s finest food market. Farm-to-table produce, artisan baked goods, game meat braais and local beer.',
    category: 'food',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-13T09:00:00')),
    endDate: ts(new Date('2026-06-13T15:00:00')),
    venueName: 'Hoffman Square',
    address: 'Charles St, Westdene',
    city: 'Bloemfontein',
    location: geo(-29.1175, 26.2184),
    totalCapacity: 800,
    totalBooked: 320,
    isFree: true,
    ticketTiers: [],
    hostId: 'host-fs-2',
    hostName: 'Bloem Food Collective',
    tags: ['food', 'market', 'farm', 'free'],
    featured: false,
    viewCount: 1100,
    saveCount: 78,
    createdAt: ts(new Date('2026-05-10')),
    updatedAt: ts(new Date('2026-05-14')),
  },

  // ── LIMPOPO ───────────────────────────────────────
  {
    id: 'mock-lp-1',
    title: 'Polokwane Food & Wine Festival',
    description: 'Limpopo\'s premium food and wine showcase. Taste the Waterberg region\'s world-class wines alongside gourmet game cuisine.',
    category: 'food',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-04T12:00:00')),
    endDate: ts(new Date('2026-07-05T20:00:00')),
    venueName: 'Meropa Casino & Entertainment World',
    address: 'N1, Polokwane',
    city: 'Polokwane',
    location: geo(-23.8962, 29.4486),
    totalCapacity: 1000,
    totalBooked: 480,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Tasting Pass', price: 40000, currency: 'ZAR', capacity: 1000, sold: 480 }],
    hostId: 'host-lp-1',
    hostName: 'Limpopo Gastronomy',
    tags: ['food', 'wine', 'gourmet', 'waterberg'],
    featured: false,
    viewCount: 1600,
    saveCount: 112,
    createdAt: ts(new Date('2026-05-12')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-lp-2',
    title: 'Kruger Bushveld Run',
    description: 'A 10K trail run through the Limpopo bushveld at the edge of the Kruger. Wildlife sightings guaranteed.',
    category: 'sports',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-11T06:00:00')),
    endDate: ts(new Date('2026-07-11T11:00:00')),
    venueName: 'Phalaborwa Gate, Kruger NP',
    address: 'Phalaborwa Gate Rd',
    city: 'Tzaneen',
    location: geo(-23.9396, 31.1551),
    totalCapacity: 200,
    totalBooked: 145,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Entry', price: 28000, currency: 'ZAR', capacity: 200, sold: 145 }],
    hostId: 'host-lp-2',
    hostName: 'Bushveld Trail Running',
    tags: ['trail run', 'kruger', 'wildlife', 'nature'],
    featured: false,
    viewCount: 1200,
    saveCount: 98,
    createdAt: ts(new Date('2026-05-13')),
    updatedAt: ts(new Date('2026-05-16')),
  },

  // ── MPUMALANGA ────────────────────────────────────
  {
    id: 'mock-mp-1',
    title: 'Panorama Route Hike & Braai',
    description: 'Guided hike along the Blyde River Canyon rim followed by a sunset braai. One of the most scenic routes in Africa.',
    category: 'sports',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-18T08:00:00')),
    endDate: ts(new Date('2026-07-18T18:00:00')),
    venueName: 'God\'s Window Viewpoint',
    address: 'R534, Graskop',
    city: 'Mbombela',
    location: geo(-24.8833, 30.8833),
    totalCapacity: 50,
    totalBooked: 38,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'All-inclusive day', price: 65000, currency: 'ZAR', capacity: 50, sold: 38 }],
    hostId: 'host-mp-1',
    hostName: 'Lowveld Adventures',
    tags: ['hike', 'braai', 'nature', 'panorama'],
    featured: false,
    viewCount: 890,
    saveCount: 72,
    createdAt: ts(new Date('2026-05-14')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-mp-2',
    title: 'Mbombela Stadium Concert',
    description: 'A massive open-air concert at Mbombela Stadium featuring Afrobeats, hip-hop and house headliners.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-25T16:00:00')),
    endDate: ts(new Date('2026-07-26T01:00:00')),
    venueName: 'Mbombela Stadium',
    address: 'Mbombela, 1200',
    city: 'Mbombela',
    location: geo(-25.4764, 30.9697),
    totalCapacity: 40000,
    totalBooked: 28000,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'General', price: 45000, currency: 'ZAR', capacity: 40000, sold: 28000 }],
    hostId: 'host-mp-2',
    hostName: 'Lowveld Concerts',
    tags: ['concert', 'stadium', 'afrobeats', 'hiphop'],
    featured: false,
    viewCount: 7800,
    saveCount: 540,
    createdAt: ts(new Date('2026-05-01')),
    updatedAt: ts(new Date('2026-05-16')),
  },

  // ── NORTH WEST ────────────────────────────────────
  {
    id: 'mock-nw-1',
    title: 'Sun City Music Extravaganza',
    description: 'Two nights of headline acts at Africa\'s entertainment capital. International and local superstars on three stages.',
    category: 'music',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-08-01T17:00:00')),
    endDate: ts(new Date('2026-08-02T02:00:00')),
    venueName: 'Sun City Superbowl',
    address: 'Sun City Resort, Rustenburg',
    city: 'Rustenburg',
    location: geo(-25.3415, 27.0957),
    totalCapacity: 6000,
    totalBooked: 4800,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Standard', price: 75000, currency: 'ZAR', capacity: 6000, sold: 4800 }],
    hostId: 'host-nw-1',
    hostName: 'Sun International Events',
    tags: ['concert', 'suncity', 'entertainment', 'resort'],
    featured: false,
    viewCount: 11000,
    saveCount: 820,
    createdAt: ts(new Date('2026-04-20')),
    updatedAt: ts(new Date('2026-05-16')),
  },
  {
    id: 'mock-nw-2',
    title: 'Rustenburg Platinum Market',
    description: 'The North West\'s largest craft and produce market. 100+ stalls of locally made goods, food and artisan products.',
    category: 'social',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-06-27T09:00:00')),
    endDate: ts(new Date('2026-06-27T16:00:00')),
    venueName: 'Rustenburg Showgrounds',
    address: 'Showgrounds Rd, Rustenburg',
    city: 'Rustenburg',
    location: geo(-25.6625, 27.2411),
    totalCapacity: 3000,
    totalBooked: 1200,
    isFree: true,
    ticketTiers: [],
    hostId: 'host-nw-2',
    hostName: 'NW Markets',
    tags: ['market', 'craft', 'free', 'family'],
    featured: false,
    viewCount: 1400,
    saveCount: 88,
    createdAt: ts(new Date('2026-05-12')),
    updatedAt: ts(new Date('2026-05-15')),
  },

  // ── NORTHERN CAPE ─────────────────────────────────
  {
    id: 'mock-nc-1',
    title: 'Kimberley Diamond City Festival',
    description: 'Celebrate the heritage of the diamond fields. Historical tours, live entertainment, artisan markets and open-air cinema.',
    category: 'festivals',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-10T10:00:00')),
    endDate: ts(new Date('2026-07-12T22:00:00')),
    venueName: 'The Big Hole Complex',
    address: 'Tucker St, Kimberley',
    city: 'Kimberley',
    location: geo(-28.7382, 24.7618),
    totalCapacity: 4000,
    totalBooked: 1900,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Festival Pass', price: 30000, currency: 'ZAR', capacity: 4000, sold: 1900 }],
    hostId: 'host-nc-1',
    hostName: 'Northern Cape Tourism',
    tags: ['festival', 'heritage', 'kimberley', 'diamonds'],
    featured: false,
    viewCount: 2200,
    saveCount: 165,
    createdAt: ts(new Date('2026-05-08')),
    updatedAt: ts(new Date('2026-05-15')),
  },
  {
    id: 'mock-nc-2',
    title: 'Upington Desert Stargazing Night',
    description: 'One of the darkest skies in the Southern Hemisphere. Expert-guided stargazing, telescope time, desert dinner under the Milky Way.',
    category: 'social',
    status: 'published',
    bannerUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80&auto=format&fit=crop',
    imageUrls: [],
    startDate: ts(new Date('2026-07-17T19:30:00')),
    endDate: ts(new Date('2026-07-17T23:30:00')),
    venueName: 'Kalahari Oranje Hotel',
    address: 'Schröder St, Upington',
    city: 'Upington',
    location: geo(-28.4478, 21.2561),
    totalCapacity: 60,
    totalBooked: 42,
    isFree: false,
    ticketTiers: [{ id: 't1', name: 'Stargazing Dinner', price: 72000, currency: 'ZAR', capacity: 60, sold: 42 }],
    hostId: 'host-nc-2',
    hostName: 'Kalahari Sky Events',
    tags: ['stargazing', 'desert', 'dinner', 'astronomy'],
    featured: false,
    viewCount: 880,
    saveCount: 74,
    createdAt: ts(new Date('2026-05-14')),
    updatedAt: ts(new Date('2026-05-16')),
  },
];

// Keep the demo calendar useful over time. Most expired seed events are rolled
// into the next four months while a few remain in the past for history views.
const DAY_MS = 24 * 60 * 60 * 1000;

export const MOCK_EVENTS: Event[] = MOCK_EVENT_SEED.map((event, index) => {
  const start = event.startDate as Date;
  const end = event.endDate as Date;
  if (end.getTime() > Date.now() || index % 9 === 0) return event;

  const futureDay = new Date(Date.now() + (3 + ((index * 5) % 120)) * DAY_MS);
  futureDay.setHours(start.getHours(), start.getMinutes(), 0, 0);
  const duration = Math.max(end.getTime() - start.getTime(), 60 * 60 * 1000);

  return {
    ...event,
    startDate: ts(futureDay),
    endDate: ts(new Date(futureDay.getTime() + duration)),
  };
});

export const MOCK_FEATURED = MOCK_EVENTS.filter((e) => e.featured);
