import React, { useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Download, Search, CheckCircle2, UserCheck } from 'lucide-react';
import { PageHeader } from '../../components/layout/PageHeader';
import { useDemoStore } from '../../store/demoStore';

export default function AttendeesPage() {
  const { id } = useParams(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all'|'checked'|'pending'>('all');
  const event = useDemoStore((state) => state.customEvents.find((item) => item.id === id)); const tickets = useDemoStore((state) => state.tickets); const checkIn = useDemoStore((state) => state.checkInTicket);
  const eventTickets = tickets.filter((ticket) => ticket.eventId === id || (!event && true));
  const visible = useMemo(() => eventTickets.filter((ticket) => (filter === 'checked' ? ticket.checkedInAtMs : filter === 'pending' ? !ticket.checkedInAtMs : true) && `${ticket.id} ${ticket.tierName}`.toLowerCase().includes(query.toLowerCase())), [eventTickets, filter, query]);
  const exportCsv = () => { const csv = ['Ticket ID,Tier,Quantity,Status,QR', ...eventTickets.map((ticket) => `${ticket.id},${ticket.tierName},${ticket.qty},${ticket.checkedInAtMs ? 'Checked in' : ticket.status},${ticket.qr}`)].join('\n'); const url = URL.createObjectURL(new Blob([csv], {type:'text/csv'})); const link = document.createElement('a'); link.href=url; link.download=`${event?.title ?? 'attendees'}-attendees.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div><PageHeader title="Attendees"/><div className="max-w-3xl mx-auto px-4 py-5"><div className="flex justify-between items-start mb-4"><div><h1 className="font-black text-text-primary">{event?.title ?? 'Demo bookings'}</h1><p className="text-xs text-text-secondary mt-1">{eventTickets.length} bookings · {eventTickets.filter((t) => t.checkedInAtMs).length} checked in</p></div><button onClick={exportCsv} className="flex gap-1.5 items-center text-xs font-black text-primary border border-primary rounded-xl px-3 py-2"><Download size={14}/> Export CSV</button></div><div className="flex gap-2 mb-4"><div className="flex-1 flex items-center gap-2 bg-white border border-app-border rounded-xl px-3"><Search size={15} className="text-muted"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search ticket or tier" className="w-full py-2.5 outline-none text-sm"/></div>{(['all','checked','pending'] as const).map((item)=><button key={item} onClick={()=>setFilter(item)} className={`px-3 rounded-xl text-xs font-black capitalize ${filter===item?'bg-primary text-white':'bg-white border border-app-border text-text-secondary'}`}>{item}</button>)}</div><div className="flex flex-col gap-2">{visible.map((ticket)=><div key={ticket.id} className="bg-white border border-app-border rounded-2xl p-4 flex items-center gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${ticket.checkedInAtMs?'bg-green-100 text-green-600':'bg-primary-light text-primary'}`}>{ticket.checkedInAtMs?<CheckCircle2 size={18}/>:<UserCheck size={18}/>}</div><div className="flex-1"><p className="font-black text-sm text-text-primary">Guest · {ticket.tierName} × {ticket.qty}</p><p className="text-xs text-text-muted font-mono mt-1">{ticket.id}</p></div>{!ticket.checkedInAtMs && ticket.status==='confirmed' && <button onClick={()=>checkIn(ticket.id)} className="text-xs font-black bg-green-500 text-white px-3 py-2 rounded-xl">Check in</button>}</div>)}{visible.length===0&&<div className="text-center py-12 text-sm text-text-muted">No attendees match this view.</div>}</div></div></div>;
}
